# Generated by Django 4.2.16 on 2024-11-17 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasapp', '0005_appointment_jitsi_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientreg',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientreg',
            name='first_name',
            field=models.CharField(default='default_value', max_length=100),
        ),
        migrations.AddField(
            model_name='patientreg',
            name='last_name',
            field=models.CharField(default='default_value', max_length=100),
        ),
    ]
