# Generated by Django 4.2.16 on 2024-11-17 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dasapp', '0007_alter_customuser_user_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientreg',
            name='email',
        ),
        migrations.RemoveField(
            model_name='patientreg',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='patientreg',
            name='last_name',
        ),
    ]
